export function isBot() {
  const userAgent = navigator.userAgent.toLowerCase();
  const botPatterns = [
    "bot",
    "crawler",
    "spider",
    "headless",
    "selenium",
    "googlebot",
    "bingbot",
    "yandexbot",
    "duckduckbot",
    "baiduspider",
    "lighthouse",
    "webdriver",
    "phantomjs",
    "puppeteer",
    "playwright",
    "nmap",
    "nikto",
    "acunetix",
    "nessus",
    "burp",
    "zap",
    "curl",
    "wget",
    "python-requests",
    "java-http-client",
    "pingdom",
    "uptimerobot",
    "newrelic",
    "datadog",
    "facebookexternalhit",
    "twitterbot",
    "linkedinbot",
    "apache-httpclient",
    "python-urllib",
    "mozilla/5.0 (compatible;)",
    "mozilla/5.0 (bot;)",
    "mozilla/5.0 (crawler;)",
    "mozilla/5.0 (spider;)",
    "mozilla/5.0 (monitoring;)",
  ];

  return botPatterns.some((pattern) => userAgent.includes(pattern));
}
